public enum SFXClips
{
	EnemyDeath = 0,
	EnemyFire = 1,
	EnemyHurt = 2,
	Checkpoint = 3,
	JumpPad = 4,
	DoorOpenClose = 5,
	LockedDoor = 6,
	Goal = 7,
	Health = 8,
	KeyCollect = 9,
	Life = 10,
	Score = 11,
	DoubleJump = 12,
	Jump = 13,
	PlayerDeath = 14,
	PlayerDeathAlternate = 15,
	PlayerHurt = 16,
	PlayerLand = 17,
	ProjectileTravel = 18,
	UIBack = 19,
	UIForward = 20,
	UISwitch = 21,
}